name: test_ci

on:
    push:
    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: buildTest
        run: make test_find_roots
        
      - name: test
        run: make test

      - name: checkFormat
        run: make cFmt
        
        
